name: Build and push Docker images

on:
  workflow_call:
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./app/backend
        push: true
        tags: ichinichi/cower_backend:latest

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./app/frontend
        push: true
        tags: ichinichi/cower_frontend:latest
        build-args: |
          BACKEND_ADDRESS=https://replace_me_in_container
