name: .NET

on:
  push:
    branches: [ "master", "develop" ]
    paths:
      - app/backend/**
  pull_request:
    branches: [ "master", "develop" ]
    paths:
      - app/backend/**

jobs:
  test:
    name: Running tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./app/backend
      
    - name: Test
      run: dotnet test ./app/backend --no-build --verbosity normal
  build:
    name: Building project
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./app/backend
      
    - name: Build
      run: dotnet build ./app/backend --no-restore
